# -*- coding: utf-8 -*-
"""20221CIT0072  1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MLRmYyGkhNIuiJnuI8y5xoMoYBBHvqer
"""

print("Hello word")

import keyword
print(keyword.kwlist)
a=len(keyword.kwlist)
print(a)

a=50
b=50
c=a+b
print(c)

L1=[1,2,3,4,5,6]
print(L1)
len(L1)

L1=[1,2,3,4,5,6]
L1.append(7)
print(L1)
L2=[8,9,10]
L3=L1+L2
print(L3)

L1=[1,1,1,2,2,2,3,3,3,4,4]
L2=[]
for x in L1:
    if x not in L2:
        L2.append(x)
L2

a=10
b=1.2

print((a))
print((b))

L1=[1,2,3,4,5,6]
print(L1[:4])

L1[-1]
L1[::-1]

a=input("enter the name")
b=a[::-1]
if a==b:
    print("palindrome")
else:
    print("not palindrome")

numbers=[1,2,3,4,5,6,7,8,9,10]
sum(numbers)

import random
numbers=[1,2,3,4,5,6,7,8,9,10]
random.shuffle(numbers)
print(numbers)

days=["monday","tuesday","wednesday","thursday","friday","saturday","sunday"]
"monday"in days
"monday"not in days

list=["red","orange","pink","black"]
print(list)
list.clear()
print(list)

nums=[1,2,3,4,1,4,1,7,8,1]
print(nums)
nums.count(1)

list_1=[1,2,3,4]
print(list_1)
list_2=list_1.copy()
print(list_2)